[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_vault = "HgJgRAkYEz1y5fx7wLkVfMSpfxuNsGgyBguXAnzkR9Qa"

[programs.devnet]
shadow_vault = "HgJgRAkYEz1y5fx7wLkVfMSpfxuNsGgyBguXAnzkR9Qa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
